language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"

env:
  - GO111MODULE=on

script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -v -mod=vendor ./...

install: true
